### PR TITLE
Hotfix types

### PR DESCRIPTION
**Pull request by jmlorenzi**
Should I send hotfix pull requests to both branches or should you handle that?

Also, is the version bump supposed to also reach the master branch?

### CODE REVIEW

**Comment by mhoffman** [comment]
Thanks for the patch, I looked through it and I think you got every kind value right now! I think we were lucky before because most of the kind_values end up being 8 on gfortran. But of course it was inconsistent before you fixed it.

As for which branch to send a pull-request to: As long as patches are small it doesn't matter too much on my end. Using the hotfix/feature convention in names is super useful since it is faster to grasp their intention. But in the end I can still merge it either way and I will decide based on the content anyhow. It is probably easier for you to double-check the diff if you send the pull-request to whichever branch you created the patch from.

**Comment by jmlorenzi** [comment]
Can I keep commenting here?

Anyhow, shouldn't hotfixes be merged into both master AND develop or discarded altogether to keep things clean? Alternative, they could be merged only to develop, but not the other way round.
Also hotfixes shouldn't always come from master and features always come from develop

**Comment by mhoffman** [comment]
I think [this graphic](http://nvie.com/posts/a-successful-git-branching-model/#hotfix-branches) is pretty much the best explanation. If a hotfix branch is successful (i.e. fixes a bug) it should merge into develop **and** master and *afterwards* be deleted. That's all.

Is your last sentence an assertion or a question?

**Comment by jmlorenzi** [comment]
It was intended to be a question. I guess that graph also answers that.

**Comment by mhoffman** [comment]
Correct, so hotfix_* should branch off `master` and feature_* should branch off `develop`.

**Pull request merged**
