### PR TITLE
otf backend

### PR DESCRIPTION
**Pull request by jmlorenzi**
Here is the first version of the otf backend, for you to take a look.
I will try to prepare some documentation and known issues text document and add it to the pull request.

Cheers
Juan

### CODE REVIEW

**Comment by jmlorenzi** [comment]
Max,

Everything seems to be in sync between the otf backend and the develop branch.

Additionally, I have performed checks, and the backend gives results compatible with those from local_smart and lat_int.
Git hub does not seem to let me upload .py files... I will email you the files to reproduce the tests. Later I would like to automatize them and add them to the repo, but right now they require human intervention to look at the result plots.
On top of that we have the import_export tests for travis-ci running.

I think this is ready to be merged into develop.

Cheers
Juan

**Comment by mhoffman** [comment]
On Wed, Mar 23, 2016 at 8:55 AM, Juan M. Lorenzi <notifications@github.com>
wrote:

> Git hub does not seem to let me upload .py files... I


??? That should not be the case. Can you tell me what you tried to upload
them? git add ... git comit git pull git push, yes/no, what happened after
each step?

Best,
Max.


-- 
Dr. Max J. Hoffmann
MAIL
Dept. of Chemical Engineering              PHONE:  +1 650 521 7187
Stanford University                                EMAIL:
maxjh@stanford.edu
4300
Shriram Center, room 315
443 Via Ortega
Stanford, CA 94035-4125
(U.S.A.)

**Comment by jmlorenzi** [comment]
Sorry, I should have been more specific... It does not let me attach .py files to comments to pull requests...
Of course I can add .py files to the repo...

**Comment by mhoffman** [comment]
Sure, I guess good alternatives are to either include in the PR itself via
commit or refer to a [Gist](https://gist.github.com/).

On Wed, Mar 23, 2016 at 9:46 AM, Juan M. Lorenzi <notifications@github.com>
wrote:

> Sorry, I should have been more specific... It does not let me attach .py
> files to comments to pull requests...
> Of course I can add .py files to the repo...
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/mhoffman/kmos/pull/31#issuecomment-200434487>
>



-- 
Dr. Max J. Hoffmann
MAIL
Dept. of Chemical Engineering              PHONE:  +1 650 521 7187
Stanford University                                EMAIL:
maxjh@stanford.edu
4300
Shriram Center, room 315
443 Via Ortega
Stanford, CA 94035-4125
(U.S.A.)

**Comment by jmlorenzi** [comment]
Well, I do not want to include those files in the repo (at least not now in their current version). I guess gist would be the right tool. But they should be in your inbox now.

**Pull request merged**
