### PR TITLE
Feature temporal acceleration

### PR DESCRIPTION
**Pull request by mieand**
Implementation of the temporal acceleration scheme proposed in: http://pubs.acs.org/doi/abs/10.1021/acs.jctc.6b00859

A first, rough documentation can be found under topic_guides: temporal_acceleration.rst

I had to redo/copy the implementation since a lot had changed in the develop branch since I started the development almost a year ago. Therefore only one commit in this branch.

Sorry, I have not run the nose and travis tests.

### CODE REVIEW

**Comment by mhoffman** [comment]
Thank you for submitting this feature! Documentation looks nice, too. I think we should make sure that the regression tests pass. I need a couple more days to look into this.

**Comment by mieand** [comment]
Hi Max,
What is this issue with the Travis build? Seems unrelated to my code.
Anything else I should do before this can be merged?

**Comment by mhoffman** [comment]
Sorry, sorry, sorry. You are right. It has nothing to do with your code.  There were just some path changes on Travis CI and a little change in the dependencies.  Things pass now on this commit 2b593333ab1ae1793ecee577c92050308686fa2a or simply my [feature_temp_acc](/mhoffman/kmos/tree/feature_temp_acc) branch. If you don't mind, could you pull those changes into your [feature_temp_acc](/mieand/kmos/tree/feature_temp_acc) branch [like so](http://stackoverflow.com/questions/7947322/preferred-github-workflow-for-updating-a-pull-request-after-code-review) and I can merge it right away.

**Comment by mieand** [comment]
Should be done now.

**Comment by mhoffman** [comment]
Thanks for contributing this feature!

**Pull request merged**
